RegisterCommand("Refresh_LOD", function()
  Citizen.CreateThread(function()
    local targetPed = GetPlayerPed(-1)
    local targetx, targety, targetz = table.unpack(GetEntityCoords(targetPed, false))
    RequestCollisionAtCoord(targetx, targety, targetz)
    RequestCollisionAtCoord(GetEntityCoords(targetPed))
    ClearAllBrokenGlass()
    ClearAllHelpMessages()
    LeaderboardsReadClearAll()
    ClearBrief()
    ClearGpsFlags()
    ClearPrints()
    ClearSmallPrints()
    ClearReplayStats()
    LeaderboardsClearCacheData()
    ClearFocus()
    ClearHdArea()
    ClearPedBloodDamage(PlayerPedId())
    ClearPedWetness(PlayerPedId())
    ClearPedEnvDirt(PlayerPedId())
    ResetPedVisibleDamage(PlayerPedId())
    while true do
      Citizen.Wait(0)
      SetNoisinessoveride(0.0)
      SuppressFrontendRenderingThisFrame()
      OverrideLodscaleThisFrame(0.0)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.0)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.1)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.2)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.3)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.4)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.5)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.6)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.7)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.8)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(0.9)
      Citizen.Wait(1)
      OverrideLodscaleThisFrame(1.0)
      break
    end
  end)
end)
